---
version: 3

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend_base: |
    RUN pip3 install --upgrade pip setuptools
  append_final:
    - RUN ls -la /etc  
